### ISSUE TITLE
GBS-8220 with HD Retrovision YPbPr Component Cable

### ISSUE THREAD

**Issue by lcsjunior** [ramapcsx2/gbs-control#41] opened 2018-07-19 12:28 UTC
Hi, I have used my GBS-8220 with HD Retrovision cable in YPbPr input. The image looks great.
I added the board Wemos D1 mini with gbs-control according to the setup guide.
However, the image is "shaky" horizontally.
Any suggestions for this?

**Comment by lcsjunior** [comment] 2018-07-20 03:30
Sorry for missing information, here they are.

![img_20180719_235204852](https://user-images.githubusercontent.com/8947621/42981460-95d13eaa-8bb2-11e8-9b3e-d5884c610670.jpg)

**Test gbs-control (with or without debug pin):**
![img_20180719_235834397](https://user-images.githubusercontent.com/8947621/42981522-e2e9fa42-8bb2-11e8-8862-d582fc706a98.jpg)
![img_20180720_240302605](https://user-images.githubusercontent.com/8947621/42981542-f33b5bc0-8bb2-11e8-8740-f213eea84748.jpg)

NTSC 
(YUV)SD mode
resetDigital
timeout
post preset done
Base: 1802 Best: 1799 Diff: -3
VSST: 281 VSSP: 282
...
HSST: 29 HSSP: 117
HSST: 28 HSSP: 116
HSST: 29 HSSP: 117
VSST: 504 VSSP: 506
VSST: 505 VSSP: 507
VSST: 506 VSSP: 508
VSST: 505 VSSP: 507
VSST: 504 VSSP: 506
VSST: 503 VSSP: 505
VSST: 502 VSSP: 504
VSST: 501 VSSP: 503
VSST: 500 VSSP: 502
VSST: 499 VSSP: 501
VSST: 500 VSSP: 502
VSST: 501 VSSP: 503
VSST: 502 VSSP: 504
VSST: 503 VSSP: 505
VSST: 504 VSSP: 506

The image did not improve when I changed the gbs-control options.

**Only HD Retrovision cable with GBS:**
![img_20180720_241155110](https://user-images.githubusercontent.com/8947621/42981697-deda6b02-8bb3-11e8-98c2-8bb592700dcf.jpg)

**Comment by ramapcsx2** [comment] 2018-07-20 06:49
> HSST: 29 HSSP: 117
HSST: 28 HSSP: 116   

Were you adjusting the horizontal / vertical sync positions manually there?
If not, then something is constantly sending commands to the chip.

> timeout   

Sync didn't become stable in a timings adjustment routine.
It did however find a value for htotal, so it seems like marginal sync from these logs.
Try the terminal commands 'wsog 4' or 'wsog 12' first

**Comment by lcsjunior** [comment] 2018-07-20 17:18
The horizontal and vertical adjustment I made manually. I also tested several adjustments.

Today I did the test as you suggested, but it did not solve:

Websocket Connected on IP: 192.168.4.100
New Input
NTSC 
(YUV)SD mode
resetDigital
Base: 1802 Best: 1799 Diff: -3
post preset done
set sog 4
set sog 12

**Comment by ramapcsx2** [comment] 2018-07-20 20:17
Is the black screen image in your first post what you get now?
It'd be best if you shot a short video of the problem. Preferably on something colourful, where the screen borders are nicely visible.

**Comment by lcsjunior** [comment] 2018-07-20 23:11
Yes, this image here is generated with gbs-control. See that the black color is with these noises. Tomorrow is Saturday here, I will take to make full tests.
I will also post the video as suggested.

![42981522-e2e9fa42-8bb2-11e8-8862-d582fc706a98](https://user-images.githubusercontent.com/8947621/43028829-8edbb570-8c58-11e8-8790-b2e70cb9bea7.jpg)

**Comment by ramapcsx2** [comment] 2018-07-20 23:57
If you have Sonic (1 or 2), check the intros and see if the overall brightness of the image goes up / down abnormally.
If that happens, the issue is a bad clamp position.

Another thing is that you mention GBS-8220. Is it the first model with 2 VGA outputs here?:
https://github.com/ramapcsx2/gbs-control/wiki/GBS-8200-Variants#original-gbs-8220
If so, the Intersil video driver chip generates some noise of its own. This can only be fixed with a hardware modification.
(Any other GBS board doesn't have this problem.)

Also, try to use a 5V power supply for the GBS (if you don't already use one).
This prevents the 1117 regulator from oscillating.

**Comment by ramapcsx2** [comment] 2018-07-23 22:11
It's odd for any TV to cause this. Maybe my output timing isn't fault tolerant enough for an aging device with reduced specs.

It's hard to tell from here, so I'm closing this as requested.

**Closed by ramapcsx2** 2018-07-23 22:11 UTC

**Comment by ramapcsx2** [comment] 2018-09-24 14:57
Oh yay, thanks for confirming. Gives me a lot more confidence in recommending the removal :)
